package com.dovile.bankspaymentstransfer.validator.checkiban_biccodes;

/**
 *
 * @author Dovile Barkauskaite <barkauskaite.dovile@gmail.com>
 */
public class Countrychars {
    //Input all ISO Country Code and sum of account digits
    private final String[] COUNTRY_CHARS={
            "AL28",
            "AD24",
            "AT20",
            "AZ28",
            "BH22",
            "BY28",
            "BE16",
            "BA20",
            "BR29",
            "BG22",
            "CR22",
            "HR21",
            "CY28",
            "CZ24",
            "DK18",
            "DO28",
            "TL23",
            "EG29",
            "EE20",
            "FO18",
            "FI18",
            "FR27",
            "GE22",
            "DE22",
            "GI23",
            "GR27",
            "GL18",
            "GT28",
            "HU28",
            "IS26",
            "IQ23",
            "IE22",
            "IL23",
            "IT27",
            "JO30",
            "KZ20",
            "XK20",
            "KW30",
            "LV21",
            "LB28",
            "LI21",
            "LT20",
            "LU20",
            "MK19",
            "MT31",
            "MR27",
            "MU30",
            "MC27",
            "MD24",
            "ME22",
            "NL18",
            "NO15",
            "PK24",
            "PS29",
            "PL28",
            "PT25",
            "QA29",
            "RO24",
            "LC32",
            "SM27",
            "SA24",
            "RS22",
            "SC31",
            "SK24",
            "SI19",
            "ES24",
            "SE24",
            "CH21",
            "TN24",
            "TR26",
            "UA29",
            "AE23",
            "GB22",
            "VA22",
            "VG24",
            "US00"
    };

    public String[] getCOUNTRY_CHARS() {
        return COUNTRY_CHARS;
    }
}
